In [2]:
import numpy as np
import h5py
import json
import pandas as pd


In [3]:
# Load sequences file
#sequences_file_path = 'C:\Users\myrsi\Documents\radar_scenes_dataset\RadarScenes\RadarScenes\data/sequences.json'
sequences_file_path = 'C:\\Users\\myrsi\\Documents\\radar_scenes_dataset\\RadarScenes\\RadarScenes\\data\\sequences.json'

with open(sequences_file_path, 'r') as f:
    data = json.load(f)

# Divide sequences into train and val sets
train_sequences = [name for name, seq in data['sequences'].items() if seq['category'] == 'train']
val_sequences = [name for name, seq in data['sequences'].items() if seq['category'] == 'validation']


#print(f'train seequences: {train_sequences}\n')
#print(f'val seequences: {val_sequences}')

In [4]:
# Collect radar data from train sequences
train_radar_data_list = []
for seq_name in train_sequences:
    # Open radar data file
    #radar_data_file_path = f'/home/mmita/Documents/radar_scenes_dataset/data/{seq_name}/radar_data.h5'
    radar_data_file_path = f'C:\\Users\\myrsi\\Documents\\radar_scenes_dataset\\RadarScenes\\RadarScenes\\data\\{seq_name}\\radar_data.h5'
    with h5py.File(radar_data_file_path, 'r') as f:
        # Get radar data
        radar_data = f['radar_data'][:]
        # Append to train radar data list
        train_radar_data_list.append(radar_data)

#print(train_radar_data_list)
#print(train_radar_data_list[:][:][:][4])
#print(len(train_radar_data_list[0]))


In [5]:
# Collect radar data from val sequences
val_radar_data_list = []
for seq_name in val_sequences:
    # Open radar data file
    #radar_data_file_path = f'/home/mmita/Documents/radar_scenes_dataset/data/{seq_name}/radar_data.h5'
    radar_data_file_path = f'C:\\Users\\myrsi\\Documents\\radar_scenes_dataset\\RadarScenes\\RadarScenes\\data\\{seq_name}\\radar_data.h5'
    with h5py.File(radar_data_file_path, 'r') as f:
        # Get radar data
        radar_data = f['radar_data'][:]
        # Append to val radar data list
        val_radar_data_list.append(radar_data)

#print(val_radar_data_list)

In [6]:
# Create an empty list to store all the train values
angle = []
rcs = []
range_sc = []
doppler_vel = []
label_id = []

# Loop through each object in train_radar_data_list
for obj in train_radar_data_list:
    # Loop through each tuple in the object
    for tup in obj:
        # Extract the values from the tuple and append them to the corresponding lists
        angle.append(tup[3])
        rcs.append(tup[4])
        range_sc.append(tup[2])
        doppler_vel.append(tup[5])
        label_id.append(tup[13])


KeyboardInterrupt: 

In [ ]:
# Create an empty list to store all the validation values
angle_v = []
rcs_v = []
range_sc_v = []
doppler_vel_v = []
label_id_v = []

# Loop through each object in val_radar_data_list
for obj in val_radar_data_list:
    # Loop through each tuple in the object
    for tup in obj:
        # Extract the values from the tuple and append them to the corresponding lists
        angle_v.append(tup[3])
        rcs_v.append(tup[4])
        range_sc_v.append(tup[2])
        doppler_vel_v.append(tup[5])
        label_id_v.append(tup[13])

In [ ]:
# Create a pandas DataFrame for training data
train_df = pd.DataFrame({'Angle': angle, 'RCS': rcs, 'Range_Sc': range_sc, 'Doppler_Vel': doppler_vel, 'Label_ID': label_id})

# Create a pandas DataFrame for validation data
val_df = pd.DataFrame({'Angle': angle_v, 'RCS': rcs_v, 'Range_Sc': range_sc_v, 'Doppler_Vel': doppler_vel_v, 'Label_ID': label_id_v})


In [ ]:
# Save training data to a CSV file
train_df.to_csv('training_data.csv', index=False)

# Save validation data to a CSV file
val_df.to_csv('validation_data.csv', index=False)



In [22]:
import pandas as pd

# Read the CSV file
df_training_data = pd.read_csv('training_data.csv')
df_validation_data = pd.read_csv('validation_data.csv')



In [ ]:
# Access the data in the DataFrame
# For example, print the first 5 rows of the DataFrame
print(df_training_data.head())

In [ ]:

# Check for NaN values
has_nan = df_training_data.isna().any().any()

# Print the result
if has_nan:
    print("There are NaN values in the DataFrame.")
else:
    print("There are no NaN values in the DataFrame.")


In [25]:
X = df_training_data[['Angle','RCS','Range_Sc','Doppler_Vel']]
y = df_training_data['Label_ID']
X_val = df_validation_data[['Angle','RCS','Range_Sc','Doppler_Vel']]
y_val = df_validation_data['Label_ID']

20028871.2

In [9]:
from sklearn.model_selection import train_test_split
val_proportion = df_validation_data.shape[0] / df_training_data.shape[0]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=val_proportion,random_state=42)

In [10]:
print("Train set shape:", X_train.shape, y_train.shape)
print("Test set shape:", X_test.shape, y_test.shape)
print("Validation set shape:", X_val.shape, y_val.shape)

Train set shape: (81300276, 4) (81300276,)
Test set shape: (18844080, 4) (18844080,)
Validation set shape: (18844080, 4) (18844080,)


In [24]:
# Turn data into tensors
# Otherwise this causes issues with computations later on
import torch
X = torch.tensor(df_training_data[['Angle', 'RCS', 'Range_Sc', 'Doppler_Vel']].values, dtype=torch.float)
y = torch.tensor(df_training_data['Label_ID'].values, dtype=torch.float)
X_val = torch.tensor(df_validation_data[['Angle','RCS','Range_Sc','Doppler_Vel']].values, dtype=torch.float)
y_val = torch.tensor(df_validation_data['Label_ID'].values, dtype=torch.float)

# View the first five samples
#X[:5], y[:5], X_val[:5], y_val[:5]
X_train.shape

torch.Size([5, 4])

In [4]:
from sklearn.model_selection import train_test_split
val_proportion = df_validation_data.shape[0] / df_training_data.shape[0]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=val_proportion,random_state=42)

In [23]:
len(X_train), len(X_test), len(X_val), len(y_train), len(y_test), len(y_val)

(81300276, 18844080, 18844080, 81300276, 18844080, 18844080)

In [5]:
# Standard PyTorch imports
import torch
from torch import nn

# Make device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [6]:
#Define the convolutional Neural Network
import torch.nn as nn
import torch.nn.functional as F

# Define the model architecture
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(4, 32, kernel_size=3)
        self.bn1 = nn.BatchNorm2d(32)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3)
        self.bn2 = nn.BatchNorm2d(64)
        self.pool1 = nn.MaxPool2d(2,2)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3)
        self.bn3 = nn.BatchNorm2d(128)
        self.conv4 = nn.Conv2d(128, 256, kernel_size=3)
        self.bn4 = nn.BatchNorm2d(256)
        self.pool2 = nn.MaxPool2d(2,2)
        
        self.upsample1 = nn.functional.interpolate  # Corrected upsampling function
        self.deconv1 = nn.ConvTranspose2d(256, 128, kernel_size=9)  # Corrected input channels
        self.bn5 = nn.BatchNorm2d(128)
        self.deconv2 = nn.ConvTranspose2d(128, 64, kernel_size=6)  # Corrected input channels
        self.bn6 = nn.BatchNorm2d(64)
        self.upsample2 = nn.functional.interpolate  # Corrected upsampling function
        self.deconv3 = nn.ConvTranspose2d(64, 32, kernel_size=5)  # Corrected input channels
        self.bn7 = nn.BatchNorm2d(32)  # Corrected input channels
        self.deconv4 = nn.ConvTranspose2d(32, 6, kernel_size=3)  # Corrected input channels

        self.dropout = nn.Dropout(p=0.5)
        self.fc1 = nn.Linear(256 * 8 * 8, 512)  # Corrected input features
        self.fc2 = nn.Linear(512, 10)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x))) 
        x = F.relu(self.bn2(self.conv2(x)))
        x = self.pool1(x)    
        x = F.relu(self.bn3(self.conv3(x))) 
        x = F.relu(self.bn4(self.conv4(x)))
        x = self.pool2(x)     

        x = self.upsample1(x, scale_factor=2, mode='bilinear', align_corners=False)
        x = F.relu(self.bn5(self.deconv1(x)))
        x = F.relu(self.bn6(self.deconv2(x)))
        x = self.upsample2(x, scale_factor=2, mode='bilinear', align_corners=False)
        x = F.relu(self.bn7(self.deconv3(x)))
        x = self.deconv4(x)

        x = x.view(-1, 256 * 8 * 8)
        x = self.dropout(F.relu(self.fc1(x)))
        x = self.softmax(self.fc2(x))

        return x

model_1 = Net().to(device)
model_1

Net(
  (conv1): Conv2d(4, 32, kernel_size=(3, 3), stride=(1, 1))
  (bn1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1))
  (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (pool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1))
  (bn3): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv4): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1))
  (bn4): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (deconv1): ConvTranspose2d(256, 128, kernel_size=(9, 9), stride=(1, 1))
  (bn5): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (deconv2): ConvTranspose2d(128, 64, kernel_size=(6, 6

In [7]:
# Define a loss function and optimizer
import torch.optim as optim

loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_1.parameters(), lr=0.001, betas=(0.9,0.999))

In [19]:
X_train.shape, X_train[:5] , y_train.shape

(torch.Size([5, 4]),
 tensor([[ 2.3665e-01,  1.3874e+01,  4.0424e+01, -3.1899e-04],
         [-2.2168e-01, -2.2579e+00,  1.4596e+01, -2.0613e-03],
         [-6.6272e-01,  5.0351e+00,  3.6930e+01, -6.7980e+00],
         [ 6.4274e-02, -4.2500e+00,  6.3856e+01,  6.5092e+00],
         [ 2.0290e-01,  2.2982e+01,  6.9704e+01, -5.9451e-04]]),
 torch.Size([5]))

In [14]:
import torch
from torch.utils.data import TensorDataset, DataLoader

torch.manual_seed(42)

# Create a TensorDataset from the training data
dataset = TensorDataset(X_train, y_train)

# Create a DataLoader with batch size 5
batch_size = 5

trainloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Set the number of epochs
num_epochs = 500
iterations_per_epoch = 1000

# Put data to target device
X_train, y_train = X_train.to(device), y_train.to(device)

# Define the training loop
for epoch in range(num_epochs):
    running_loss = 0.0
    
    # Iterate over the data loader for the specified number of iterations per epoch
    for i, (X_train, y_train) in enumerate(trainloader, 1):        

        # Zero the gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model_1(X_train)

        # Compute the loss
        loss = loss_fn(outputs, y_train)

        # Backward pass
        loss.backward()

        # Update the weights
        optimizer.step()

        # Accumulate the loss
        running_loss += loss.item()

        # Print statistics every 2000 mini-batches
        if i % 2000 == 0:
            print(f"Epoch: {epoch+1}/{num_epochs} | Iteration: {i}/{iterations_per_epoch} | Loss: {running_loss / i:.5f}")

    # Print epoch-wise statistics
    print(f"Epoch: {epoch+1}/{num_epochs} | Loss: {running_loss / iterations_per_epoch:.5f}")

print('Finished Training')

RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [5, 4]

In [38]:
X_train, y_train


(tensor([[ 1.0195e+00, -8.6274e+00,  8.6475e+00,  2.6316e-03],
         [-2.5642e-01, -1.2110e+01,  2.4821e+01, -7.1202e+00],
         [-7.4001e-01,  9.3935e+00,  6.0843e+01, -1.7778e-03],
         ...,
         [ 8.9021e-01, -3.3762e+00,  6.5599e+00,  4.6159e+00],
         [-1.9560e-02, -1.6377e+01,  3.7548e+01, -4.3199e+00],
         [-4.9341e-01, -6.6121e+00,  3.8605e+01, -4.3854e+00]]),
 tensor([11., 11., 11.,  ..., 11., 11., 11.]))